version: '3.9'

services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: adm
      MYSQL_PASSWORD: mda
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
